spring:
  application:
    name: london-gateway
    
server:
  port: ${PORT:8080}
  
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DISCOVERY_URL:http://localhost:8761/eureka/}
      
ribbon:
   ReadTimeout: 60000
      
zuul:
  ignoredServices: '*'
  routes:
    inspector-lestrade:
      path: /oauth2/**
      serviceId: inspector-lestrade
      stripPrefix: false
      sensitiveHeaders: Cookie,Set-Cookie
    john-watson:
      path: /john-watson/**
      serviceId: john-watson