zuul:
  ignoredServices: '*'
  routes:
    inspector-lestrade:
      path: /oauth2/**
      serviceId: inspector-lestrade
      url: ${INSPECTOR_LESTRADE_URL}
      stripPrefix: false
      sensitiveHeaders: Cookie,Set-Cookie
    john-watson:
      path: /john-watson/**
      serviceId: john-watson
      url: ${JOHN_WATSON_URL}